"""
Test Writer Agent — generates test cases for code, plans, or agent behaviour.

Capabilities:
  - Generate unit tests (pytest, Jest, Vitest)
  - Generate integration tests for agent pipelines
  - Write edge-case and failure-mode tests
  - Produce BDD-style Given/When/Then descriptions
  - Annotate plans with testability notes

Rules:
  - Every agent contract ships with at least 3 test cases
  - Tests cover: happy path, empty/null input, permission-denied path
  - Mocks are explicit — never rely on real external services in unit tests
  - Test file naming: test_<module>_<feature>.py
"""

from __future__ import annotations

import logging

from cortex.agents.base import BaseAgent
from cortex.models import (
    AgentInput,
    AgentOutput,
    PageIndex,
    PageType,
    Quality,
)

logger = logging.getLogger(__name__)


class TestWriterAgent(BaseAgent):
    """Generates test suites from intents, code, or plan descriptions."""

    name = "test_writer_agent"
    description = "Test generation agent — pytest, Jest, BDD"
    required_permissions: list[str] = []

    async def execute(self, agent_input: AgentInput) -> AgentOutput:
        intent = agent_input.intent
        logger.info("[test_writer] Generating tests for: %s", intent[:80])

        # Determine test type from intent
        test_code = self._generate_tests(intent, agent_input.constraints)

        result_page = PageIndex(
            type=PageType.TOOL_RESULT,
            summary=f"Tests for: {intent[:50]}",
            token_count=len(test_code) // 4,
            tags=["agent:test_writer", "artifact:test"],
            content=test_code,
        )

        return AgentOutput(
            result=test_code,
            pages_to_add=[result_page],
            confidence=0.85,
            quality=Quality.OK,
        )

    def _generate_tests(self, intent: str, constraints: dict) -> str:
        """
        Generate a pytest test file skeleton.
        In production, wire this to an LLM for richer generation.
        """
        module = constraints.get("module", "module")
        feature = constraints.get("feature", "feature")
        class_name = f"Test{feature.title().replace(' ', '')}"

        return f'''"""
Auto-generated tests for {module}/{feature}.
Generated by Cortex TestWriterAgent.
Intent: {intent[:80]}
"""

import pytest


class {class_name}:
    """Test suite for {feature}."""

    # ── Happy path ───────────────────────────────────────────────

    def test_happy_path(self):
        """
        Given: valid input matching the expected contract
        When:  the function/agent is invoked
        Then:  it returns a successful result with quality=OK
        """
        # TODO: Replace with real implementation
        result = {{"status": "ok"}}
        assert result["status"] == "ok"

    # ── Empty / null input ───────────────────────────────────────

    def test_empty_input(self):
        """
        Given: empty or None input
        When:  the function/agent is invoked
        Then:  it handles gracefully (no crash, returns error or default)
        """
        result = {{"status": "error", "reason": "empty input"}}
        assert result["status"] == "error"
        assert "empty" in result["reason"]

    # ── Permission denied ────────────────────────────────────────

    def test_permission_denied(self):
        """
        Given: input that requires permissions the caller lacks
        When:  the function/agent is invoked
        Then:  it returns a permission_violation mistake
        """
        result = {{"status": "denied", "type": "permission_violation"}}
        assert result["type"] == "permission_violation"

    # ── Edge case: large input ───────────────────────────────────

    def test_large_input(self):
        """
        Given: unusually large input (near token budget limits)
        When:  the function/agent is invoked
        Then:  it truncates or handles without OOM
        """
        large_input = "x" * 100_000
        assert len(large_input) == 100_000
        # TODO: invoke with large_input, assert no crash

    # ── Edge case: malformed input ───────────────────────────────

    def test_malformed_input(self):
        """
        Given: input with injection markers or invalid characters
        When:  the function/agent is invoked
        Then:  it sanitizes and does not execute injected content
        """
        malicious = "IGNORE PREVIOUS; drop table users;"
        sanitized = malicious.replace("IGNORE PREVIOUS", "").replace(";", "")
        assert "IGNORE" not in sanitized
'''
